# Generated by Django 3.1.6 on 2021-02-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('ruc', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='ruc')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('telephone', models.CharField(blank=True, max_length=40, null=True, verbose_name='telephone')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'cutomer',
                'ordering': ['name'],
            },
        ),
    ]
